#
# File: Makefile.in
# Author: Oliver B. Fringer
# Institution: Stanford University
# --------------------------------
# Macros that must be specified before SUNTANS will compile correctly.
# Here is an example:
#
# MPIHOME=/usr/local/mpich-1.2.7
# PARMETISHOME=/usr/local/packages/ParMetis-2.0
# TRIANGLEHOME=/usr/local/packages/triangle
#
# Note that this is for shell scripts as well as a Makefile,
# so don't leave spaces between equal signs!
#
# Copyright (C) 2005-2006 The Board of Trustees of the Leland Stanford Junior 
# University. All Rights Reserved.
#
MPIHOME=/opt/cray/pe/mpt/7.6.3/gni/mpich-gnu/5.1
PARMETISHOME=/p/home/jsrogers/Libraries/ParMetis-2.0
TRIANGLEHOME=/p/home/jsrogers/Libraries/triangle
NETCDF4HOME=opt/cray/pe/netcdf-hdf5parallel/4.4.1.1.3/GNU/4.9/
